name: streak_reminder

on:
  schedule:
    - cron:  '00 17 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install bs4
        run: python3 -m pip install bs4
      - name: Install requests
        run: python3 -m pip install requests
      - name: Install lxml
        run: python3 -m pip install lxml
      - name: Run email code
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          GIT_HUB_USER_1_EMAIL_ID: ${{ secrets.GIT_HUB_USER_1_EMAIL_ID }}
          GIT_HUB_USER_1_USER_NAME: ${{ secrets.GIT_HUB_USER_1_USER_NAME }}
          GIT_HUB_USER_2_EMAIL_ID: ${{ secrets.GIT_HUB_USER_2_EMAIL_ID }}
          GIT_HUB_USER_2_USER_NAME: ${{ secrets.GIT_HUB_USER_2_USER_NAME }}
        run: python3 send_email.py
