name: streak_reminder

on:
  schedule:
    - cron:  '0 21 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install bs4
        run: python3 -m pip install bs4
      - name: Install requests
        run: python3 -m pip install requests
      - name: Run email code
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          GIT_HUB_USERS: ${{ secrets.GIT_HUB_USERS }}
        run: python3 send_email.py